name: ivoy_challenge
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  provider: ^6.0.3

dev_dependencies:
  artemis: '>=7.0.0'
  build_runner: ^2.0.3
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  gql: 0.13.0
  json_serializable: ^4.1.2
  meta: '>=1.0.0 <2.0.0'

flutter:
  uses-material-design: true
